// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: match/v1/external.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalMatchResultState int32

const (
	ExternalMatchResultState_EXTERNAL_MATCH_RESULT_STATE_UNKNOWN ExternalMatchResultState = 0
	// The result is currently being computed
	ExternalMatchResultState_EXTERNAL_MATCH_RESULT_STATE_PENDING ExternalMatchResultState = 1
	// The result was properly computed and is no longer running
	ExternalMatchResultState_EXTERNAL_MATCH_RESULT_STATE_COMPLETED ExternalMatchResultState = 2
	// An error occurrend during the computation of that result
	// See error_msg field for details related to that error
	ExternalMatchResultState_EXTERNAL_MATCH_RESULT_STATE_ERRORED ExternalMatchResultState = 3
)

// Enum value maps for ExternalMatchResultState.
var (
	ExternalMatchResultState_name = map[int32]string{
		0: "EXTERNAL_MATCH_RESULT_STATE_UNKNOWN",
		1: "EXTERNAL_MATCH_RESULT_STATE_PENDING",
		2: "EXTERNAL_MATCH_RESULT_STATE_COMPLETED",
		3: "EXTERNAL_MATCH_RESULT_STATE_ERRORED",
	}
	ExternalMatchResultState_value = map[string]int32{
		"EXTERNAL_MATCH_RESULT_STATE_UNKNOWN":   0,
		"EXTERNAL_MATCH_RESULT_STATE_PENDING":   1,
		"EXTERNAL_MATCH_RESULT_STATE_COMPLETED": 2,
		"EXTERNAL_MATCH_RESULT_STATE_ERRORED":   3,
	}
)

func (x ExternalMatchResultState) Enum() *ExternalMatchResultState {
	p := new(ExternalMatchResultState)
	*p = x
	return p
}

func (x ExternalMatchResultState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalMatchResultState) Descriptor() protoreflect.EnumDescriptor {
	return file_match_v1_external_proto_enumTypes[0].Descriptor()
}

func (ExternalMatchResultState) Type() protoreflect.EnumType {
	return &file_match_v1_external_proto_enumTypes[0]
}

func (x ExternalMatchResultState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalMatchResultState.Descriptor instead.
func (ExternalMatchResultState) EnumDescriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{0}
}

type ExternalMatchRefreshOnce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Exact time at which the refresh will ocurr
	At *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
}

func (x *ExternalMatchRefreshOnce) Reset() {
	*x = ExternalMatchRefreshOnce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMatchRefreshOnce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMatchRefreshOnce) ProtoMessage() {}

func (x *ExternalMatchRefreshOnce) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMatchRefreshOnce.ProtoReflect.Descriptor instead.
func (*ExternalMatchRefreshOnce) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalMatchRefreshOnce) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type ExternalMatchRefreshDaily struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time at which the refresh will start occuring
	StartAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	// Time at which the refresh will stop occuring
	EndAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *ExternalMatchRefreshDaily) Reset() {
	*x = ExternalMatchRefreshDaily{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMatchRefreshDaily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMatchRefreshDaily) ProtoMessage() {}

func (x *ExternalMatchRefreshDaily) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMatchRefreshDaily.ProtoReflect.Descriptor instead.
func (*ExternalMatchRefreshDaily) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalMatchRefreshDaily) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *ExternalMatchRefreshDaily) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type ExternalMatchRefreshAdhoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExternalMatchRefreshAdhoc) Reset() {
	*x = ExternalMatchRefreshAdhoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMatchRefreshAdhoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMatchRefreshAdhoc) ProtoMessage() {}

func (x *ExternalMatchRefreshAdhoc) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMatchRefreshAdhoc.ProtoReflect.Descriptor instead.
func (*ExternalMatchRefreshAdhoc) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{2}
}

type ExternalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organization string `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	IconUrl      string `protobuf:"bytes,2,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Url          string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// A mapping keyed by endpoint names to their actual urls
	// It is useful, so that we won't be hardcoding the
	// endpoints in the optable-cli, which means changing
	// the routes, does not require the cli to be updated
	Endpoints map[string]string `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExternalInfo) Reset() {
	*x = ExternalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalInfo) ProtoMessage() {}

func (x *ExternalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalInfo.ProtoReflect.Descriptor instead.
func (*ExternalInfo) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{3}
}

func (x *ExternalInfo) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *ExternalInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ExternalInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalInfo) GetEndpoints() map[string]string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type CreateExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// identifier shared between the two parties for matching
	MatchUid    string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Mostly for display concern,
	// since spawning runs is always controlled by the sender
	//
	// Types that are assignable to RefreshFrequency:
	//	*CreateExternalMatchReq_Once
	//	*CreateExternalMatchReq_Daily
	//	*CreateExternalMatchReq_Adhoc
	RefreshFrequency isCreateExternalMatchReq_RefreshFrequency `protobuf_oneof:"refresh_frequency"`
	// Subset of IdKind to use for matching. If empty, all IDs elligible for matching will be used.
	IdentifiersFilter []IdKind `protobuf:"varint,17,rep,packed,name=identifiers_filter,json=identifiersFilter,proto3,enum=match.v1.IdKind" json:"identifiers_filter,omitempty"`
}

func (x *CreateExternalMatchReq) Reset() {
	*x = CreateExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalMatchReq) ProtoMessage() {}

func (x *CreateExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalMatchReq.ProtoReflect.Descriptor instead.
func (*CreateExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{4}
}

func (x *CreateExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

func (x *CreateExternalMatchReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExternalMatchReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (m *CreateExternalMatchReq) GetRefreshFrequency() isCreateExternalMatchReq_RefreshFrequency {
	if m != nil {
		return m.RefreshFrequency
	}
	return nil
}

func (x *CreateExternalMatchReq) GetOnce() *ExternalMatchRefreshOnce {
	if x, ok := x.GetRefreshFrequency().(*CreateExternalMatchReq_Once); ok {
		return x.Once
	}
	return nil
}

func (x *CreateExternalMatchReq) GetDaily() *ExternalMatchRefreshDaily {
	if x, ok := x.GetRefreshFrequency().(*CreateExternalMatchReq_Daily); ok {
		return x.Daily
	}
	return nil
}

func (x *CreateExternalMatchReq) GetAdhoc() *ExternalMatchRefreshAdhoc {
	if x, ok := x.GetRefreshFrequency().(*CreateExternalMatchReq_Adhoc); ok {
		return x.Adhoc
	}
	return nil
}

func (x *CreateExternalMatchReq) GetIdentifiersFilter() []IdKind {
	if x != nil {
		return x.IdentifiersFilter
	}
	return nil
}

type isCreateExternalMatchReq_RefreshFrequency interface {
	isCreateExternalMatchReq_RefreshFrequency()
}

type CreateExternalMatchReq_Once struct {
	Once *ExternalMatchRefreshOnce `protobuf:"bytes,4,opt,name=once,proto3,oneof"`
}

type CreateExternalMatchReq_Daily struct {
	Daily *ExternalMatchRefreshDaily `protobuf:"bytes,5,opt,name=daily,proto3,oneof"`
}

type CreateExternalMatchReq_Adhoc struct {
	Adhoc *ExternalMatchRefreshAdhoc `protobuf:"bytes,6,opt,name=adhoc,proto3,oneof"`
}

func (*CreateExternalMatchReq_Once) isCreateExternalMatchReq_RefreshFrequency() {}

func (*CreateExternalMatchReq_Daily) isCreateExternalMatchReq_RefreshFrequency() {}

func (*CreateExternalMatchReq_Adhoc) isCreateExternalMatchReq_RefreshFrequency() {}

type CreateExternalMatchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the same match_uid as received in the request
	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *CreateExternalMatchRes) Reset() {
	*x = CreateExternalMatchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExternalMatchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalMatchRes) ProtoMessage() {}

func (x *CreateExternalMatchRes) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalMatchRes.ProtoReflect.Descriptor instead.
func (*CreateExternalMatchRes) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExternalMatchRes) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type ExternalMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid    string                 `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Results     []*ExternalMatchResult `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ExternalMatch) Reset() {
	*x = ExternalMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMatch) ProtoMessage() {}

func (x *ExternalMatch) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMatch.ProtoReflect.Descriptor instead.
func (*ExternalMatch) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalMatch) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

func (x *ExternalMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalMatch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExternalMatch) GetResults() []*ExternalMatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListExternalMatchReq) Reset() {
	*x = ListExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalMatchReq) ProtoMessage() {}

func (x *ListExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalMatchReq.ProtoReflect.Descriptor instead.
func (*ListExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{7}
}

type ListExternalMatchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*ExternalMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *ListExternalMatchRes) Reset() {
	*x = ListExternalMatchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExternalMatchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalMatchRes) ProtoMessage() {}

func (x *ListExternalMatchRes) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalMatchRes.ProtoReflect.Descriptor instead.
func (*ListExternalMatchRes) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{8}
}

func (x *ListExternalMatchRes) GetMatches() []*ExternalMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetExternalMatchResultsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *GetExternalMatchResultsReq) Reset() {
	*x = GetExternalMatchResultsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExternalMatchResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalMatchResultsReq) ProtoMessage() {}

func (x *GetExternalMatchResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalMatchResultsReq.ProtoReflect.Descriptor instead.
func (*GetExternalMatchResultsReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{9}
}

func (x *GetExternalMatchResultsReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type GetExternalMatchResultsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ExternalMatchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetExternalMatchResultsRes) Reset() {
	*x = GetExternalMatchResultsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExternalMatchResultsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalMatchResultsRes) ProtoMessage() {}

func (x *GetExternalMatchResultsRes) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalMatchResultsRes.ProtoReflect.Descriptor instead.
func (*GetExternalMatchResultsRes) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{10}
}

func (x *GetExternalMatchResultsRes) GetResults() []*ExternalMatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RunExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid             string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
	MatchResultUid       string `protobuf:"bytes,2,opt,name=match_result_uid,json=matchResultUid,proto3" json:"match_result_uid,omitempty"`
	ClientCertificatePem string `protobuf:"bytes,3,opt,name=client_certificate_pem,json=clientCertificatePem,proto3" json:"client_certificate_pem,omitempty"`
}

func (x *RunExternalMatchReq) Reset() {
	*x = RunExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExternalMatchReq) ProtoMessage() {}

func (x *RunExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExternalMatchReq.ProtoReflect.Descriptor instead.
func (*RunExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{11}
}

func (x *RunExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

func (x *RunExternalMatchReq) GetMatchResultUid() string {
	if x != nil {
		return x.MatchResultUid
	}
	return ""
}

func (x *RunExternalMatchReq) GetClientCertificatePem() string {
	if x != nil {
		return x.ClientCertificatePem
	}
	return ""
}

type RunExternalMatchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchResultUid       string `protobuf:"bytes,1,opt,name=match_result_uid,json=matchResultUid,proto3" json:"match_result_uid,omitempty"`
	Endpoint             string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ServerCertificatePem string `protobuf:"bytes,3,opt,name=server_certificate_pem,json=serverCertificatePem,proto3" json:"server_certificate_pem,omitempty"`
	ErrorMsg             string `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

func (x *RunExternalMatchRes) Reset() {
	*x = RunExternalMatchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunExternalMatchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExternalMatchRes) ProtoMessage() {}

func (x *RunExternalMatchRes) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExternalMatchRes.ProtoReflect.Descriptor instead.
func (*RunExternalMatchRes) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{12}
}

func (x *RunExternalMatchRes) GetMatchResultUid() string {
	if x != nil {
		return x.MatchResultUid
	}
	return ""
}

func (x *RunExternalMatchRes) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RunExternalMatchRes) GetServerCertificatePem() string {
	if x != nil {
		return x.ServerCertificatePem
	}
	return ""
}

func (x *RunExternalMatchRes) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetExternalMatchResultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchResultUid string `protobuf:"bytes,1,opt,name=match_result_uid,json=matchResultUid,proto3" json:"match_result_uid,omitempty"`
}

func (x *GetExternalMatchResultReq) Reset() {
	*x = GetExternalMatchResultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExternalMatchResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalMatchResultReq) ProtoMessage() {}

func (x *GetExternalMatchResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalMatchResultReq.ProtoReflect.Descriptor instead.
func (*GetExternalMatchResultReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{13}
}

func (x *GetExternalMatchResultReq) GetMatchResultUid() string {
	if x != nil {
		return x.MatchResultUid
	}
	return ""
}

type GetExternalMatchResultRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchResult *ExternalMatchResult `protobuf:"bytes,1,opt,name=match_result,json=matchResult,proto3" json:"match_result,omitempty"`
}

func (x *GetExternalMatchResultRes) Reset() {
	*x = GetExternalMatchResultRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExternalMatchResultRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalMatchResultRes) ProtoMessage() {}

func (x *GetExternalMatchResultRes) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalMatchResultRes.ProtoReflect.Descriptor instead.
func (*GetExternalMatchResultRes) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{14}
}

func (x *GetExternalMatchResultRes) GetMatchResult() *ExternalMatchResult {
	if x != nil {
		return x.MatchResult
	}
	return nil
}

type ExternalMatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string                   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	State     ExternalMatchResultState `protobuf:"varint,2,opt,name=state,proto3,enum=match.v1.ExternalMatchResultState" json:"state,omitempty"`
	ErrorMsg  string                   `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Insights  *Insights                `protobuf:"bytes,4,opt,name=insights,proto3" json:"insights,omitempty"`
	CreatedAt *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ExternalMatchResult) Reset() {
	*x = ExternalMatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMatchResult) ProtoMessage() {}

func (x *ExternalMatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMatchResult.ProtoReflect.Descriptor instead.
func (*ExternalMatchResult) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{15}
}

func (x *ExternalMatchResult) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ExternalMatchResult) GetState() ExternalMatchResultState {
	if x != nil {
		return x.State
	}
	return ExternalMatchResultState_EXTERNAL_MATCH_RESULT_STATE_UNKNOWN
}

func (x *ExternalMatchResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ExternalMatchResult) GetInsights() *Insights {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *ExternalMatchResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExternalMatchResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PauseExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *PauseExternalMatchReq) Reset() {
	*x = PauseExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseExternalMatchReq) ProtoMessage() {}

func (x *PauseExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseExternalMatchReq.ProtoReflect.Descriptor instead.
func (*PauseExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{16}
}

func (x *PauseExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type ResumeExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *ResumeExternalMatchReq) Reset() {
	*x = ResumeExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeExternalMatchReq) ProtoMessage() {}

func (x *ResumeExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeExternalMatchReq.ProtoReflect.Descriptor instead.
func (*ResumeExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type LockExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *LockExternalMatchReq) Reset() {
	*x = LockExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockExternalMatchReq) ProtoMessage() {}

func (x *LockExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockExternalMatchReq.ProtoReflect.Descriptor instead.
func (*LockExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{18}
}

func (x *LockExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type UnlockExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *UnlockExternalMatchReq) Reset() {
	*x = UnlockExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockExternalMatchReq) ProtoMessage() {}

func (x *UnlockExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockExternalMatchReq.ProtoReflect.Descriptor instead.
func (*UnlockExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{19}
}

func (x *UnlockExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

type ArchiveExternalMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUid string `protobuf:"bytes,1,opt,name=match_uid,json=matchUid,proto3" json:"match_uid,omitempty"`
}

func (x *ArchiveExternalMatchReq) Reset() {
	*x = ArchiveExternalMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_v1_external_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveExternalMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveExternalMatchReq) ProtoMessage() {}

func (x *ArchiveExternalMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_external_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveExternalMatchReq.ProtoReflect.Descriptor instead.
func (*ArchiveExternalMatchReq) Descriptor() ([]byte, []int) {
	return file_match_v1_external_proto_rawDescGZIP(), []int{20}
}

func (x *ArchiveExternalMatchReq) GetMatchUid() string {
	if x != nil {
		return x.MatchUid
	}
	return ""
}

var File_match_v1_external_proto protoreflect.FileDescriptor

var file_match_v1_external_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x17, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x73, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x18, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x4f, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x61, 0x74,
	0x22, 0x85, 0x01, 0x0a, 0x19, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x12, 0x35,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x41, 0x64, 0x68, 0x6f, 0x63, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63,
	0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63,
	0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x43, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x3c, 0x0a, 0x0e,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf5, 0x02, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x04, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4f, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x05, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x12,
	0x3b, 0x0a, 0x05, 0x61, 0x64, 0x68, 0x6f, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64,
	0x68, 0x6f, 0x63, 0x48, 0x00, 0x52, 0x05, 0x61, 0x64, 0x68, 0x6f, 0x63, 0x12, 0x3f, 0x0a, 0x12,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x11, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x13, 0x0a,
	0x11, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x79, 0x22, 0x35, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x0d, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x22,
	0x49, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x92, 0x01, 0x0a,
	0x13, 0x52, 0x75, 0x6e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x50, 0x65,
	0x6d, 0x22, 0xae, 0x01, 0x0a, 0x13, 0x52, 0x75, 0x6e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x34, 0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x45, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x28, 0x0a, 0x10, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xa4, 0x02, 0x0a, 0x13, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x08, 0x69, 0x6e, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52,
	0x08, 0x69, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x34, 0x0a, 0x15, 0x50, 0x61, 0x75, 0x73, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x14,
	0x4c, 0x6f, 0x63, 0x6b, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69,
	0x64, 0x22, 0x35, 0x0a, 0x16, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x17, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x69, 0x64,
	0x2a, 0xc0, 0x01, 0x0a, 0x18, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x23, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f,
	0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e,
	0x41, 0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x29, 0x0a, 0x25, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43,
	0x48, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x27, 0x0a, 0x23, 0x45, 0x58,
	0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x45,
	0x44, 0x10, 0x03, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_match_v1_external_proto_rawDescOnce sync.Once
	file_match_v1_external_proto_rawDescData = file_match_v1_external_proto_rawDesc
)

func file_match_v1_external_proto_rawDescGZIP() []byte {
	file_match_v1_external_proto_rawDescOnce.Do(func() {
		file_match_v1_external_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_v1_external_proto_rawDescData)
	})
	return file_match_v1_external_proto_rawDescData
}

var file_match_v1_external_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_match_v1_external_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_match_v1_external_proto_goTypes = []interface{}{
	(ExternalMatchResultState)(0),      // 0: match.v1.ExternalMatchResultState
	(*ExternalMatchRefreshOnce)(nil),   // 1: match.v1.ExternalMatchRefreshOnce
	(*ExternalMatchRefreshDaily)(nil),  // 2: match.v1.ExternalMatchRefreshDaily
	(*ExternalMatchRefreshAdhoc)(nil),  // 3: match.v1.ExternalMatchRefreshAdhoc
	(*ExternalInfo)(nil),               // 4: match.v1.ExternalInfo
	(*CreateExternalMatchReq)(nil),     // 5: match.v1.CreateExternalMatchReq
	(*CreateExternalMatchRes)(nil),     // 6: match.v1.CreateExternalMatchRes
	(*ExternalMatch)(nil),              // 7: match.v1.ExternalMatch
	(*ListExternalMatchReq)(nil),       // 8: match.v1.ListExternalMatchReq
	(*ListExternalMatchRes)(nil),       // 9: match.v1.ListExternalMatchRes
	(*GetExternalMatchResultsReq)(nil), // 10: match.v1.GetExternalMatchResultsReq
	(*GetExternalMatchResultsRes)(nil), // 11: match.v1.GetExternalMatchResultsRes
	(*RunExternalMatchReq)(nil),        // 12: match.v1.RunExternalMatchReq
	(*RunExternalMatchRes)(nil),        // 13: match.v1.RunExternalMatchRes
	(*GetExternalMatchResultReq)(nil),  // 14: match.v1.GetExternalMatchResultReq
	(*GetExternalMatchResultRes)(nil),  // 15: match.v1.GetExternalMatchResultRes
	(*ExternalMatchResult)(nil),        // 16: match.v1.ExternalMatchResult
	(*PauseExternalMatchReq)(nil),      // 17: match.v1.PauseExternalMatchReq
	(*ResumeExternalMatchReq)(nil),     // 18: match.v1.ResumeExternalMatchReq
	(*LockExternalMatchReq)(nil),       // 19: match.v1.LockExternalMatchReq
	(*UnlockExternalMatchReq)(nil),     // 20: match.v1.UnlockExternalMatchReq
	(*ArchiveExternalMatchReq)(nil),    // 21: match.v1.ArchiveExternalMatchReq
	nil,                                // 22: match.v1.ExternalInfo.EndpointsEntry
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
	(IdKind)(0),                        // 24: match.v1.IdKind
	(*Insights)(nil),                   // 25: match.v1.Insights
}
var file_match_v1_external_proto_depIdxs = []int32{
	23, // 0: match.v1.ExternalMatchRefreshOnce.at:type_name -> google.protobuf.Timestamp
	23, // 1: match.v1.ExternalMatchRefreshDaily.start_at:type_name -> google.protobuf.Timestamp
	23, // 2: match.v1.ExternalMatchRefreshDaily.end_at:type_name -> google.protobuf.Timestamp
	22, // 3: match.v1.ExternalInfo.endpoints:type_name -> match.v1.ExternalInfo.EndpointsEntry
	1,  // 4: match.v1.CreateExternalMatchReq.once:type_name -> match.v1.ExternalMatchRefreshOnce
	2,  // 5: match.v1.CreateExternalMatchReq.daily:type_name -> match.v1.ExternalMatchRefreshDaily
	3,  // 6: match.v1.CreateExternalMatchReq.adhoc:type_name -> match.v1.ExternalMatchRefreshAdhoc
	24, // 7: match.v1.CreateExternalMatchReq.identifiers_filter:type_name -> match.v1.IdKind
	16, // 8: match.v1.ExternalMatch.results:type_name -> match.v1.ExternalMatchResult
	7,  // 9: match.v1.ListExternalMatchRes.matches:type_name -> match.v1.ExternalMatch
	16, // 10: match.v1.GetExternalMatchResultsRes.results:type_name -> match.v1.ExternalMatchResult
	16, // 11: match.v1.GetExternalMatchResultRes.match_result:type_name -> match.v1.ExternalMatchResult
	0,  // 12: match.v1.ExternalMatchResult.state:type_name -> match.v1.ExternalMatchResultState
	25, // 13: match.v1.ExternalMatchResult.insights:type_name -> match.v1.Insights
	23, // 14: match.v1.ExternalMatchResult.created_at:type_name -> google.protobuf.Timestamp
	23, // 15: match.v1.ExternalMatchResult.updated_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_match_v1_external_proto_init() }
func file_match_v1_external_proto_init() {
	if File_match_v1_external_proto != nil {
		return
	}
	file_match_v1_identifier_proto_init()
	file_match_v1_insights_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_match_v1_external_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMatchRefreshOnce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMatchRefreshDaily); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMatchRefreshAdhoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExternalMatchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExternalMatchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExternalMatchResultsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExternalMatchResultsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunExternalMatchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExternalMatchResultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExternalMatchResultRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_v1_external_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveExternalMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_match_v1_external_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*CreateExternalMatchReq_Once)(nil),
		(*CreateExternalMatchReq_Daily)(nil),
		(*CreateExternalMatchReq_Adhoc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_v1_external_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_v1_external_proto_goTypes,
		DependencyIndexes: file_match_v1_external_proto_depIdxs,
		EnumInfos:         file_match_v1_external_proto_enumTypes,
		MessageInfos:      file_match_v1_external_proto_msgTypes,
	}.Build()
	File_match_v1_external_proto = out.File
	file_match_v1_external_proto_rawDesc = nil
	file_match_v1_external_proto_goTypes = nil
	file_match_v1_external_proto_depIdxs = nil
}
